main : ${project.groupId}.cmdsigns.CmdSigns
name: CmdSigns
version: ${project.version}
description: ${project.description}
author: ${project.author}
softdepend: [Vault]
commands:
  cmdsigns:
    description: Main CmdSigns command.
    usage: /<command> [reload|loadtemplates|info]
    aliases: [cmdsign]
  signs:
    description: Displays the signs templates menu.
    usage: /<command>
    aliases: [templates]